### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by madmax17** [konstantinkobs/brackets-SASShints#9]
I press $ and nothing is happening, not showing any of my variables. Maybe a conflict with some other extension?

**Comment by Wikunia** [comment]
Can you provide the logs using the Brackets Developer Tools?

**Comment by madmax17** [comment]
Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90

PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
2/command/Menus.js:820
Error setting menu item shortcut: 1
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/SASSAgent.js:161:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90 

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/main.js:323:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.<anonymous> (file:///C:/Users/Mad%20Max/AppData/Roaming/Brackets/extensions/user/enturn.quick-search/main.js:216:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.<anonymous> (file:///C:/Users/Mad%20Max/AppData/Roaming/Brackets/extensions/user/globals/main.js:16:3)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at Object.<anonymous> (file:///C:/Users/Mad%20Max/AppData/Roaming/Brackets/extensions/user/soimon.brackets-document-outliner/main.js:49:29)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
http://online-dnbard.rhcloud.com/tick/5620f410e59615263f000006/8e8fd7f6a50368340a232b91d87e829f Failed to load resource: net::ERR_NAME_NOT_RESOLVED
trackingClient.js:35 Can't track online status, retry in 5 mins
http://online-dnbard.rhcloud.com/tick/54f1f443646174009a090000/8e8fd7f6a50368340a232b91d87e829f Failed to load resource: net::ERR_NAME_NOT_RESOLVED
OnlineTracking.js:56 Can't track online status, retry in 5 mins
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:126:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:127:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at Object.eval (/./ParfaitAPI.js:128:5)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at _statusChangeHandler (/SASSAgent.js:141:49)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _setStatus (/LiveDevelopment/LiveDevelopment.js:332:17)
    at Object.init (/LiveDevelopment/LiveDevelopment.js:1495:9)
    at eval (/LiveDevelopment/main.js:309:25)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
main.js:543 AppInit
/utils/DeprecationWarning.js:90

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:474:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at file:///C:/Users/Mad%20Max/AppData/Roaming/Brackets/extensions/user/acb-bootstrap-snippets/main.js:267:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:284:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done](file:///C:/Program%20Files%20%28x86%29/Brackets/www/thirdparty/thirdparty.min.js:556:27220)
    at Object.d.always (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:28096)
/command/KeyBindingManager.js:749
Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp/command/KeyBindingManager.js:749 _addBinding
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown/command/KeyBindingManager.js:749 _addBinding
/command/Menus.js:820 Error setting menu item shortcut: 1

It keeps repeating the Deprecated message.
